services:
  players-api:
    build: ./players
    restart: always
    expose:
      - 8080
    depends_on:
      - players-db
    networks: 
      - player-market
  players-db:
    build: ./players_db
    restart: always
    expose:
      - 3306
    networks: 
      - player-market
    environment:
      MYSQL_DATABASE: players_db
      MYSQL_USER: players_db_user
      MYSQL_PASSWORD: players_db_pass
      MYSQL_ROOT_PASSWORD: players_db_pass

  teams-api:
    build: ./teams
    restart: always
    expose:
      - 8080
    depends_on:
      - teams-db
    networks: 
      - player-market
  teams-db:
    build: ./teams_db
    restart: always
    expose:
      - 3306
    networks: 
      - player-market
    environment:
      MYSQL_DATABASE: teams_db
      MYSQL_USER: teams_db_user
      MYSQL_PASSWORD: teams_db_pass
      MYSQL_ROOT_PASSWORD: teams_db_pass
  proxy:
    build: ./proxy
    restart: always
    networks:
      - player-market
    ports:
      - "8080:80"

networks: 
  player-market:
    driver: bridge

